services:

  nginx:
    image: "nginx:latest"
    hostname: nginx
    ports:
      - 443:443
      - 80:80
      - 1883:1883
      - 1884:1884
      - 9001:9001
      - 18083:18083
      - 27017:27017
    networks:
      - influx-network
      - api-network
      - mongodb-network
      - mosquitto-network
      - eagle-app-network
      - vaultwarden-network
      - ghost-network
      - emqx-network
      - bookstack-app-network
      - uptime-kuma-network
      - authentik-server-network
      - keycloak-network
      - shlink-network
    restart: always
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_LOGS_DIR}:/var/log/nginx
      - ${NGINX_LETSENCRYPT_DIR}:/etc/letsencrypt
    env_file:
      - .env

  api:
    build:
      context: ./repos/telemetry-api
      dockerfile: Dockerfile
    hostname: "api"
    networks:
      - api-network
    restart: always
    volumes:
      - api-temp-data:/app/tmp
      - ${API_CONF_FILE}:/app/secrets/config.yaml
    environment:
      - CONFIG_PATH=/app/secrets/config.yaml

  eagle-app:
    build:
      context: ./repos/eagle-app
      dockerfile: Dockerfile
    hostname: eagle-app
    networks:
      - eagle-app-network
      - mosquitto-network
      - mongodb-network
    restart: always
    env_file:
      - .eagle-app.env

  influx:
    image: "influxdb:latest"
    hostname: "influx"
    networks:
      - influx-network
    restart: always
    volumes:
      - influx-varlib-data:/var/lib/influxdb2
      - influx-etc-data:/etc/influxdb2

  mongodb:
    image: "mongo:latest"
    hostname: "mongodb"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-network

  mosquitto:
    image: "eclipse-mosquitto"
    hostname: "mosquitto"
    restart: always
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mosquitto-network 

  emqx:
    image: "emqx"
    hostname: "emqx"
    restart: always
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-etc-data:/opt/emqx/etc
    networks:
      - emqx-network

  influx-logger:
    build:
      context: ./repos/influx-logger
      dockerfile: Dockerfile
    volumes:
      - ${INFLUX_LOGGER_CONF_FILE}:/configuration.json
    networks:
      - influx-network
      - mosquitto-network
      - api-network
    restart: always

  vaultwarden:
    image: "vaultwarden/server"
    hostname: "vaultwarden"
    environment:
      - DOMAIN=https://vaultwarden.eagletrt.it
    volumes: 
      - ./private/vaultwarden/vw-data:/data/
    networks:
      - vaultwarden-network 
    restart: unless-stopped

  ghost:
    image: "ghost"
    hostname: "ghost"
    environment:
      - NODE_ENV=development
    volumes:
      - ghost-data:/var/lib/ghost/content
      - ./configs/ghost.json:/var/lib/ghost/config.production.json
    networks:
      - ghost-network
    restart: unless-stopped

  bookstack-app:
    image: "lscr.io/linuxserver/bookstack"
    hostname: bookstack-app
    environment:
      - APP_URL=https://docs.eagletrt.it 
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${BOOKSTACK_DB_PASS}
      - DB_DATABASE=bookstackapp
    env_file:
      - './.bookstack.env'
    volumes:
      - ./private/bookstack_app:/config
    networks:
      - bookstack-app-network
      - bookstack-db-network
    restart: always
    depends_on:
      - bookstack-db

  bookstack-db:
    image: "lscr.io/linuxserver/mariadb"
    hostname: "bookstack-db"
    environment:
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_DB_PASS}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASS}
    volumes:
      - ./private/bookstack_db:/config
    networks:
      - bookstack-db-network
    restart: always

  uptime-kuma:
    image: "louislam/uptime-kuma:1"
    hostname: "uptime-kuma"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./private/uptime_kuma:/app/data
    networks:
      - uptime-kuma-network
    restart: unless-stopped

  authentik:
    image: 'ghcr.io/goauthentik/server:2024.4.2'
    command: 'server'
    container_name: 'authentik'
    hostname: 'authentik'
    restart: 'unless-stopped'
    environment:
      - 'AUTHENTIK_SECRET_KEY=b3BlbnNzbCByYW5kIDYwCg=='
      - 'AUTHENTIK_REDIS__HOST=authentik-redis'
      - 'AUTHENTIK_POSTGRESQL__HOST=authentik-postgres'
      - 'AUTHENTIK_POSTGRESQL__USER=authentik'
      - 'AUTHENTIK_POSTGRESQL__PASSWORD=authentik'
      - 'AUTHENTIK_POSTGRESQL__NAME=authentik'
      - 'AUTHENTIK_COOKIE_DOMAIN=eagletrt.it'
      - 'AUTHENTIK_ERROR_REPORTING__ENABLED=false'
    volumes:
      - './private/authentik/media:/media'
      - './private/authentik/templates:/templates'
    networks:
      - 'authentik-network'
      - 'authentik-server-network'
      - 'authentik-redis-network'
      - 'authentik-postgres-network'

  authentik-worker:
    image: 'ghcr.io/goauthentik/server:2024.4.2'
    command: 'worker'
    container_name: 'authentik-worker'
    restart: 'unless-stopped'
    environment:
      - 'AUTHENTIK_SECRET_KEY=b3BlbnNzbCByYW5kIDYwCg=='
      - 'AUTHENTIK_REDIS__HOST=authentik-redis'
      - 'AUTHENTIK_POSTGRESQL__HOST=authentik-postgres'
      - 'AUTHENTIK_POSTGRESQL__USER=authentik'
      - 'AUTHENTIK_POSTGRESQL__PASSWORD=authentik'
      - 'AUTHENTIK_POSTGRESQL__PORT=5432'
      - 'AUTHENTIK_POSTGRESQL__NAME=authentik'
      - 'AUTHENTIK_ERROR_REPORTING__ENABLED=true'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './private/authentik/media:/media'
      - './private/authentik/templates:/templates'
    networks:
      - 'authentik-network'
      - 'authentik-redis-network'
      - 'authentik-postgres-network'
    user: 'root'

  authentik-redis:
    image: 'redis'
    container_name: 'authentik-redis'
    hostname: 'authentik-redis'
    restart: 'unless-stopped'
    volumes:
      - './private/authentik/redis/data:/data'
    networks:
      - 'authentik-redis-network'

  authentik-postgres:
    image: 'postgres:12-alpine'
    container_name: 'authentik-postgres'
    hostname: 'authentik-postgres'
    restart: 'unless-stopped'
    ports:
      - '5432:5432'
    volumes:
      - './private/authentik/postgres/data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=authentik'
      - 'POSTGRES_PASSWORD=authentik'
      - 'POSTGRES_DB=authentik'
    networks:
      - 'authentik-postgres-network'

  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    command: 'start'
    hostname: 'keycloak'
    restart: 'unless-stopped'
    networks:
      - 'keycloak-network'
    depends_on:
      - 'keycloak-mariadb'
    environment:
      KC_DB: mariadb 
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_HOST: keycloak-mariadb
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false 
      KC_HOSTNAME_URL: https://idp.eagletrt.it

  keycloak-mariadb:
    image: 'mariadb:latest'
    hostname: 'keycloak-mariadb'
    restart: 'unless-stopped'
    networks:
      - 'keycloak-network'
    volumes:
      - './private/keycloak_mariadb/data:/var/lib/mysql'
    environment:
      MARIADB_DATABASE: keycloak
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: keycloak

  shlink:
    image: 'shlinkio/shlink'
    hostname: 'shlink'
    restart: 'unless-stopped'
    user: 'root'
    volumes:
      - './private/shlink/data:/etc/shlink/data:rw'
    networks:
      - 'shlink-network'
    environment:
      DEFAULT_DOMAIN: 'eagletrt.it'
      IS_HTTPS_ENABLED: true

networks:
  api-network:
  influx-network:
  mongodb-network:
  mosquitto-network:
  eagle-app-network:
  vaultwarden-network:
  ghost-network:
  emqx-network:
  bookstack-app-network:
  bookstack-db-network:
  uptime-kuma-network:
  authentik-network:
  authentik-server-network:
  authentik-redis-network:
  authentik-postgres-network:
  keycloak-network:
  shlink-network:
volumes:
  influx-varlib-data:
  influx-etc-data:
  mongodb-data:
  api-temp-data:
  ghost-data:
  emqx-data:
  emqx-etc-data:
