version: "3.8"
services:

  nginx:
    image: "nginx:latest"
    hostname: nginx
    ports:
      - 443:443
      - 80:80
      - 1883:1883
    networks:
      - influx-network
      - api-network
    restart: always
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ${INFLUX_CERTS_DIR}:/var/certs/influx
      - ${API_CERTS_DIR}:/var/certs/api
    env_file:
      - .env

  api:
    build:
      context: ./repos/telemetry-api
      dockerfile: Dockerfile
    hostname: "api"
    networks:
      - api-network
    restart: always
    volumes:
      - api-temp-data:/app/tmp
      - ${API_CONF_FILE}:/app/secrets/config.yaml
    environment:
      - CONFIG_PATH=/app/secrets/config.yaml

  influx:
    image: "influxdb:latest"
    hostname: "influx"
    networks:
      - influx-network
    restart: always
    volumes:
      - influx-data:/data

networks:
  api-network:
  influx-network:
volumes:
  influx-data:
  api-temp-data:
