version: "3.8"
services:

  nginx:
    image: "nginx:latest"
    hostname: nginx
    ports:
      - 443:443
      - 80:80
      - 1883:1883
      - 27017:27017
      - 1884:1884
      - 9001:9001
    networks:
      - influx-network
      - api-network
      - mongodb-network
      - mosquitto-network
      - eagle-app-network
    restart: always
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ${INFLUX_CERTS_DIR}:/var/certs/influx
      - ${API_CERTS_DIR}:/var/certs/api
      - ${EAGLE_APP_CERTS_DIR}:/var/certs/eagle-app
    env_file:
      - .env

  api:
    build:
      context: ./repos/telemetry-api
      dockerfile: Dockerfile
    hostname: "api"
    networks:
      - api-network
    restart: always
    volumes:
      - api-temp-data:/app/tmp
      - ${API_CONF_FILE}:/app/secrets/config.yaml
    environment:
      - CONFIG_PATH=/app/secrets/config.yaml

  eagle-app:
    build:
      context: ./repos/eagle-app
      dockerfile: Dockerfile
    hostname: eagle-app
    networks:
      - eagle-app-network
      - mosquitto-network
      - mongodb-network
    restart: always
    env_file:
      - .eagle-app.env

  influx:
    image: "influxdb:latest"
    hostname: "influx"
    networks:
      - influx-network
    restart: always
    volumes:
      - influx-varlib-data:/var/lib/influxdb2
      - influx-etc-data:/etc/influxdb2

  mongodb:
    image: "mongo:latest"
    hostname: "mongodb"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-network

  mosquitto:
    image: "eclipse-mosquitto"
    hostname: "mosquitto"
    restart: always
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mosquitto-network 

networks:
  api-network:
  influx-network:
  mongodb-network:
  mosquitto-network:
  eagle-app-network:
volumes:
  influx-varlib-data:
  influx-etc-data:
  api-temp-data:
  mongodb-data:
